In [4]:
# import libraries and load the dataset
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings("ignore")

digits = load_digits()

In [5]:
# split the dataset into train set and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [6]:
# Logistic Regression Classifier
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [7]:
# support vector machine classifier
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [8]:
# random forest classifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [9]:
# k fold
from sklearn.model_selection import KFold

kf = KFold(n_splits=3) # 3 folds will be created
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)


# Similar to K-Fold but it is little better
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [19]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], \
    digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [20]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [21]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [22]:
scores_rf

[0.9348914858096828, 0.9532554257095158, 0.9248747913188647]

In [23]:
# sklearn comes with this heacy lifting processes
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target) # model, X, y

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [24]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [25]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92777778, 0.91944444, 0.95264624, 0.96935933, 0.9275766 ])